### ISSUE TITLE
Support multi line header

### ISSUE THREAD

**Issue by GoogleCodeExporter** [joeha480/obfl#12]
```
In order to fully support duplex rendering combined with double line spacing, 
multi line headers are needed.

The solution can keep the requirement that fields must fit within its space on 
a single row.
```

Original issue reported on code.google.com by `joel.hak...@mtm.se` on 22 Nov 2013 at 2:25

**Comment by bertfrees** [comment]
It appears that multiple header lines is one of the requirements in our project. See the examples from Celia at http://snaekobbi.github.io/requirements/pagination/index.xhtml#4.5:81. The requirement is multiple lines of actual text, not just blank lines in order to create an offset for support duplex rendering combined with double line spacing (which is already supported).
